services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RAPIDAPI_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString

databases:
  - name: your-db-name
    plan: free 