services:
  - type: web
    name: metrics-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.server.app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://kelzodb_user:b9WCxmKsbZSTq0EYqGJ6aM0wU7Nl4ege@dpg-cv5cv77noe9s73egtus0-a.oregon-postgres.render.com/kelzodb
      - key: PORT
        value: 10000

databases:
  - name: your-db-name
    plan: free 